### ISSUE TITLE
gatsby-remark-* plugin support

### ISSUE THREAD

**Issue by KyleAMathews** [ChristopherBiscardi/gatsby-mdx#10]
It'd be awesome if it could support gatsby-remark-* plugins so it instantly has image support, etc. Not 100% sure if possible so if not, reimplement a similar API.

**Comment by LeKoArts** [comment]
Would also be interested in that so that people can use my plugin with their React components:
https://github.com/LeKoArts/gatsby-remark-design-system

**Comment by avigoldman** [comment]
After some quick digging, it looks like this should be possible if we process the mdx files as plain markdown, process it through the gatsby-remark-* plugins, and convert it back to markdown before handing it over to MDX.

We'll have to do that in both the loader and AST generation in `extend-node-type.js`.

**Comment by youngboy** [comment]
haven't try with `gatsby-remark-image` plugin, but I just play a bit with `gatsby-mdx` image support, and only found out two ways to handle add image to mdx for now

1. use webpack loader
```jsx
import pic from './pic'

<img src={pic} alt='12' />
```
2. use page query to query image processed by sharp relate plugin
ideally we should map each `img` tag with `StaticQuery`, but unfortunately it is not support query variables, but maybe we can have it later ? see https://github.com/gatsbyjs/gatsby/issues/6596

so as a workaround I use `PageQuery` together with `React.Context`
```jsx
// layout
export const ImageContext = React.createContext('images');
import { ImageContext } from './Layout'

const Mdxayout = (props) => {
  const { data,  children } = props
  return (
        <ImageContext.Provider value={data}>
          {children}
        </ImageContext.Provider>
  )

// mdx
import Layout from '../components/Layout'
import Img from 'gatsby-image'

export default Layout

export const query = graphql`
query CollectionPic {
  file(relativePath: { eq: "pic.jpg" }) {
    childImageSharp{
      fluid(maxWidth: 320) {
        ...GatsbyImageSharpFluid
      }
    }
  }
}
`
  <ImageContext.Consumer>
    {data => {
      return <Img fluid={data.file.childImageSharp.fluid} alt='pic-alt' />
    }}
  </ImageContext.Consumer>
```

**Comment by jquense** [comment]
MDX works out of the box with remark plugins, I think the best strategy would be to _try_ and write the gatsby remark plugins as plain remark plugins? I know that doesn't really work, but maybe there is a way to do both, e.g. wrap in gatsby plugin for the gatsby specific work and move the remark ast stuff to proper plugins? 

In that case both gatsby-remark, and gatsby-mdx could implement the same convention for consuming sub-plugins? Or maybe gatsby-mdx could be handed directly to the gatsby remark-plugin

**Comment by ChristopherBiscardi** [comment]
@jquense there are a few classes of plugins right now. 

1. remark, rehype, and anything else supported directly in mdx can be passed in as the typical options, which get passed through directly:
```js
{
  ...
  mdPlugins: [],
  hastPlugins: []
  ...
}
```
2. gatsby-plugins that use `setParserPlugins`. These can be added to the `mdPlugins` array following similar syntax to the way the remark-transformer does it [code in PR](https://github.com/ChristopherBiscardi/gatsby-mdx/pull/68/files#diff-16077ea40133e9c00ceab5dee7c5e91bR168).
```js
// extend-node-type
options.mdPlugins.push(parserPlugin);
```
3. gatsby plugins that [mutateSource](https://github.com/gatsbyjs/gatsby/blob/30f7ac487e3503efe27a96e34e59b66e2ae4cd6b/packages/gatsby-transformer-remark/src/extend-node-type.js#L117-L126). This is where it starts to get tricky because we're passing in the full markdown node, all of the files sourced by gatsby, the getNode function and the cache. Which means there's a potentially huge surface area for people to depend on the structure of the markdownNode, any given file, any? node. I haven't seen a plugin that implements mutateSource yet though so need someone to point one out if they're aware of one.
4. Pretty much the same as 3, except it calling the required module [directly with slightly different argument](https://github.com/gatsbyjs/gatsby/blob/30f7ac487e3503efe27a96e34e59b66e2ae4cd6b/packages/gatsby-transformer-remark/src/extend-node-type.js#L180-L195)

TBD on how many plugins we can support by passing in the AST at the right stage in the pipeline, but that's the current approach I'm taking for full gatsby-remark-* support.

**Comment by jquense** [comment]
nice breakdown :thumbsup: its mainly **3** i think we can consolidate or make compatible i think. Ideally (i think we'd agree) i't be great if all the gatsby remark prism, image, etc plugins worked interchangably between `gatsby-transformer-remark` and `gatsby-mdx`, I think @KyleAMathews would agree that we can make neded changes upstream in gatsby to facilitate that, but the question is what is the best strategy for doing so. I think that moving as much of the gatsby plugin logic into real remark plugins (as is possible) is a good first step. 

On top of that it may make sense to build hooks into the remark transformer so that mdx can be a child plugin, or maybe just a common set of conventions so all the existing child remark gatsby plugins (prism, images, etc) could be added to gatsby-mdx same as they are to the transformer

**Comment by ChristopherBiscardi** [comment]
I worked out support for #4 today in https://github.com/ChristopherBiscardi/gatsby-mdx/pull/68 [on the stream](https://www.twitch.tv/videos/300615843) today by basically using a closure to encapsulate the scope and apply a new [programmatically created remark plugin](https://github.com/ChristopherBiscardi/gatsby-mdx/pull/68/files#diff-c6a30b82431172cf30a847d67fa0b918R51) for each gatsby-remark plugin.

The problems are no longer the differing interfaces, but rather the interface between the plugins and the mdx parser. For example, gatsby-remark-prismjs outputs html into the tree but mdx isn't escaping it at that point in the pipeline so we need to apply a new remark plugin to convert html into jsx for html nodes. (otherwise mdx will choke on things like `<span>{</span>` which are valid html but indicate an opening of a code expression for jsx)

**Comment by ChristopherBiscardi** [comment]
gatsby-remark-* plugin support was released in 0.1.1.

Anyone who has custom plugins or uses gatsby-remark-* plugins can test it out by following the config shown in the [custom-remark-plugins example](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/examples/custom-remark-plugins/gatsby-config.js).

As we discover edge cases for plugins, they should go into their own issues so we can knock them down one by one. I expect that there will be issues as we get through the long-tail of plugin compatibility and I know of at least one instance of the autolink header misapplying styles because it uses `class` and not `className`. By contrast, the prism and katex plugins seem to be fully operational.

We also need to follow up with mdx-js and push some parsing changes upstream so we can get them out of gatsby-mdx and into core mdx.

**Comment by alexchantastic** [comment]
@youngboy's method (https://github.com/ChristopherBiscardi/gatsby-mdx/issues/10#issuecomment-409606726) no longer seems to work (v0.1.4).

```jsx
import pic from './pic.jpg'

<img src={pic} alt='12' />
```

Has this method been deprecated in favor of using [gatsby-remark-images](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images)?

**Comment by alexchantastic** [comment]
@ChristopherBiscardi thanks for the prompt reply. I did a little bit more digging and this might be an issue with mdx-js itself in that inline JSX doesn't seem to work properly.

This:

```jsx
import image from './my-image.png;

<img src={image} />
<img src={`http://www.my-website.com/my-image.png`} />
<img src="http://www.my-website.com/my-image.png" />
```

Outputs this:

```html
<img src="{image}">
<img src="{`http://www.my-website.com/my-image.png`}">
<img src="http://www.my-website.com/my-image.png">
```

These seem to be the relevant issues in mdx-js: https://github.com/mdx-js/mdx/issues/246 https://github.com/mdx-js/mdx/issues/222
