### ISSUE TITLE
Error: The page component must export a React component for it to be valid

### ISSUE THREAD

**Issue by fredrik-sogaard** [ChristopherBiscardi/gatsby-mdx#119]
**Describe the bug**
I have some simple .mdx files in a `/pages/work` directory. Everything runs on `gatsby develop` but when I try to build it with `gatsby build` I get this 
`[/src/pages/work/project-name.mdx] The page component must export a React component for it to be valid`

I have this in gatsby-config (nothing in gatsby-node):
```
{
      resolve: 'gatsby-mdx',
      options: {
        defaultLayouts: {
          work: require.resolve('./src/layouts/work.js')
        }
      }
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages/work`,
        name: 'work'
      }
    },
    'gatsby-plugin-offline',
    'gatsby-plugin-styled-components',
    'gatsby-transformer-sharp',
    'gatsby-remark-copy-linked-files',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 1440,
              linkImagesToOriginal: false,
              backgroundColor: 'transparent'
            }
          }
        ]
      }
    }
```
I've updated all dependencies. From package.json:
```
    "@mdx-js/mdx": "^0.15.2",
    "@mdx-js/tag": "^0.15.0",
    "babel-plugin-styled-components": "^1.6.4",
    "gatsby": "2.0.0-rc.15",
    "gatsby-mdx": "^0.1.3",
    "gatsby-plugin-manifest": "next",
    "gatsby-plugin-mdx": "^1.0.1",
    "gatsby-plugin-offline": "2.0.0-rc.6",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-styled-components": "^3.0.0-rc.1",
    "gatsby-remark-copy-linked-files": "^1.5.37",
    "gatsby-remark-images": "^1.5.67",
    "gatsby-source-filesystem": "^1.5.39",
    "gatsby-transformer-remark": "^1.7.44",
    "gatsby-transformer-sharp": "^1.6.27",
    "react": "^16.5.0",
    "react-dom": "^16.5.0",
```

**Comment by ChristopherBiscardi** [comment]
I noticed you're including `gatsby-mdx` *and* `gatsby-plugin-mdx`. `gatsby-plugin-mdx` isn't compatible with the v2 releases of gatsby and it also applies a webpack loader for mdx files that may conflict with `gatsby-mdx`

**Comment by silvenon** [comment]
I'm also getting that on `gatsby build` (I'm not using `gatsby-plugin-mdx`). However, for me those are only warnings and my site works fine. 🤔 

I'll try to narrow down my project and provide an actual demo.

**Comment by macklinu** [comment]
A demo of the issue that we could clone and test would be awesome. 👍 

@fredrik-sogaard would you be able to share the source of an `.mdx` file as well as the source for the `src/layouts/work.js` file?

**Comment by ChristopherBiscardi** [comment]
My guess is that this is related to the way we did page support. I originally wrote page support to work with the pagecreator plugin that comes with gatsby itself, but the officially recommended way is to layer a filesystem source over src/pages and handle the createPages ourselves. That should get rid of this warning.

because createPage [reads the content using fs and not require in a node process](https://github.com/gatsbyjs/gatsby/blob/66101ca07011c5504368ad03aa2e8fd3df5a7d57/packages/gatsby/src/redux/actions.js#L260) and [checks for export strings](https://github.com/gatsbyjs/gatsby/blob/66101ca07011c5504368ad03aa2e8fd3df5a7d57/packages/gatsby/src/redux/actions.js#L269-L271) it can't tell that an mdx file is "a real page" after it passes through webpack. It's a neat hack that works for raw JS-like files, but not files that don't looks like JS files when viewed before the webpack compilation process.

In the end, the warning is ignorable and will most likely be eliminated by #62

**Comment by silvenon** [comment]
Yeah, that seems to be exactly what's happening. That check is happening before the MDX file is compiled. It's an ugly warning, but doesn't cause an error and everything works.

**Comment by fredrik-sogaard** [comment]
I'm closing this. I reported it as an error because our build was failing and we mistakenly thought is was this warning. Turns out there was another issue causing it.

**Comment by alexchantastic** [comment]
I seem to be getting this error now. Any help would be appreciated!

Here's a link to reproduce on the minimal repo: https://github.com/alexchantastic/gatsby-mdx-minimal-repro/tree/missing_export

As similarly described in the original issue, the error occurs on `gatsby build` but not `gatsby develop`. Am I misinterpreting how to use MDX layouts?

**Comment by silvenon** [comment]
It seems that the error happens when `defaultLayouts.default` matches a page in `src/pages`. For programmatically created pages this is only a warning. It works when I remove `defaultLayouts` and explicitly export `components/layouts.js` in each page as default. All dependencies in the repro are up-to-date.

Sorry, this is not a solution, I'm just confirming the conditions under which the error happens.

**Comment by silvenon** [comment]
Feel free to open a new issue, referencing this one.
