### ISSUE TITLE
Programmatically created pages can not find relative modules

### ISSUE THREAD

**Issue by loremipson** [ChristopherBiscardi/gatsby-mdx#130]
Programmatically created pages using `gatsby-source-filesystem` and `gatsby-node` do not compile out and report the following error:

```
 ERROR  Failed to compile with 1 errors
This relative module was not found:
* ../components/ComponentName in ./.cache/gatsby-mdx/remote-mdx-dir/274ea027f0097ae07efafb9fd9c71cc6.js
```

**To Reproduce**
- Follow the docs guide for [programmatically creating pages](https://gatsby-mdx.netlify.com/guides/programmatically-creating-pages)
- Have one of your pages try and import a component via relative path:
`import Component from '../relative/path'`

What is making me scratch my head a bit here is `.cache`. Why is it looking in there? Is that expected behavior? In my graphiql interface, the `code.scope` query returns that it's in `.cache` too.

**Comment by loremipson** [comment]
Looking through the docs example, it looks like we need to set up an alias via webpack for this.

**Comment by ChristopherBiscardi** [comment]
yes as you've found, this is expected. Since you can create nodes from remote resources like contentful, relative paths don't really make sense for programmatically created nodes. We also do some behind-the-scenes work to make the scope of an mdx file available to the content, since we have to run them through webpack and also send it down to the browser.

The webpack alias is currently the officially recommended way to access other modules since it can work for remote content as well as local.

**Comment by ChristopherBiscardi** [comment]
This is the webpack config:

```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"]
    }
  });
};
```

To go a bit further on why this is the case, to get the MDX scope that is imported we have to have a way to push the imports through webpack so that they're properly handled as modules and included in the eventual MDX usage. To do this we generate a wrapper that wraps the regular component (using componentWithMDXScope) and do some processing to the scope. The scope and the wrapper get written to files in .cache/gatsby-mdx and the wrapper is the component returned from the `componentWithMDXScope` call. The wrapper imports the scope and the original wrapper, so pretty much everything works as advertised, but relative imports are sourced from the .cache directory.

Theoretically we could rewrite the relative paths to account for the wrapper moving to .cache but we haven't done that yet and we're doing some behind the scenes logic changes in #123 so probably won't make that change until afterwards.

**Comment by loremipson** [comment]
Excellent explanation, thank you!
