### ISSUE TITLE
Unpublish or document gatsby-plugin-mdx

### ISSUE THREAD

**Issue by avigoldman** [ChristopherBiscardi/gatsby-mdx#134]
We have https://github.com/ChristopherBiscardi/gatsby-plugin-mdx which is published to the Gatsby plugin directory.

We should either unpublish it when Gatsby 2.0 get its first release or document it to point people to gatsby-mdx.

**Comment by ChristopherBiscardi** [comment]
unpublish it from the gatsby-plugin list you mean? can we even do that since it relies on npm tags?

@kylematthews was asking us to rename this to `gatsby-plugin-mdx`, so I'm thinking that when we hit 1.0 here we have a discussion around the functionality included in this plugin and decide whether to publish as `gatsby-plugin-mdx` 2.0 or not. We'll have to think about all the redirects and repository change at that time if we do it, but I don't think it's important to do right now.

Also, that package has ~60 downloads per week right now and gatsby-mdx is approaching 500 so I'm not sure this is really a large issue right now (and the old repository is archived already)

**Comment by johno** [comment]
What's the status on this issue and naming for 1.0 @ChristopherBiscardi?

**Comment by ChristopherBiscardi** [comment]
Planning on doing the name conversion with the "1.0" release as we migrate into the gatsby core repo.

Tactically, there was a `1.0.1` release of `gatsby-plugin-mdx` so we should deprecate the 1.0 and 1.0.1 releases before `1.1.0` or whatever version we choose to release as. `gatsby-plugin-mdx` has 235 lifetime downloads according to the gatsby plugins page, so there will be little-to-no disruption no matter what we choose to do here.

**Comment by ChristopherBiscardi** [comment]
We'll also need to do a gatsby-mdx release to update the README to point to gatsby-plugin-mdx. Perhaps we can ship a warning in the console on install.

**Comment by ChristopherBiscardi** [comment]
gatsby-plugin-mdx is gatsby-mdx 1.0
