### ISSUE TITLE
Investigate defaultLayouts for posts in kitchen-sink example

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#151]
Need to update the kitchen-sink example content and make sure the defaultLayouts for posts are applying correctly (defaultLayouts for pages are applying).

**Comment by mcallistersean** [comment]
Was this closed because it was supposed to work now?
I don't quite understand how defaultLayouts (apart from the default key) are supposed to work, as I need to do the whole onCreateNode and createPages dance anyway for gatsby to pick up .mdx files outside of the src/pages directory. In createPages I then need to select a  component (with MDXProvider) manually anyway.
Any clarification would be welcome, I guess I'm just doing something wrong.

**Comment by ChristopherBiscardi** [comment]
@mcallistersean If you're using `createPages` and your .mdx files are outside of `src/pages` you can safely ignore the `defaultLayouts`. They are there for people who want to use the `src/pages` support and not use `createPages`. `defaultLayouts` in that case will apply an MDX layout (which is the default export in an MDX file) to a group of files at a time, reducing the burden of having to import and re-export an MDX layout in every file.
