### ISSUE TITLE
Check gatsby-mdx against the official gatsby tutorial

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#155]
Possible incompatibilities with the official gatsby starter -- https://github.com/gatsbyjs/gatsby/issues/8395

We should be a "drop in replacement" for remark in that tutorial.

**Comment by rdrey** [comment]
I think I've worked my way to a spot where `gatsby-mdx` basically replaces `gatsby-transformer-remark`. I could write it up in the docs if you like?

My last remaining issue: pages created with `createPages` don't refresh when I edit the underlying `.mdx`, but I believe that's fixed in https://github.com/ChristopherBiscardi/gatsby-mdx/pull/123?

**Comment by ChristopherBiscardi** [comment]
yeah, we'll be pulling that out of #123 into a PR sooner but the refresh is related to that for sure.

Would definitely accept a PR talking about the changes. Use an mdx file in [examples/docs/content/guides](https://github.com/ChristopherBiscardi/gatsby-mdx/tree/0ddef5952d22e3131818e05ec806e0b67b690c67/examples/docs/content/guides)

**Comment by ChristopherBiscardi** [comment]
This should be a tutorial in the new docs

**Comment by johno** [comment]
Added as a todo to add in gatsbyjs/gatsby#11361
