### ISSUE TITLE
StaticQuery warning when using componentWithMDXScope

### ISSUE THREAD

**Issue by falconmick** [ChristopherBiscardi/gatsby-mdx#166]
I've started to use this plugin and I've found that when I use componentWithMDXScope I get the following Gatsby Warning:

```
warningExported queries are only executed for Page components. Instead of an exported
 The GraphQL query in the non-page component "/Users/falconmick/dev/gatsby-blog/src/templates/BlogPostTemplate.js" will not be run.
query, either co-locate a GraphQL fragment and compose that fragment into the
query (or other fragment) of the top-level page that renders this component, or
use a <StaticQuery> in this component. For more info on fragments and
composition, see http://graphql.org/learn/queries/#fragments and for more
information on <StaticQuery>, see https://gatsbyjs.org/docs/static-query
```

Of which makes perfect sense given it looks like this is some sort of HOF that uses babel magic and then renders my component that I pass it + extracts the pageQuery. The issue is that when you render my Component, Gatsby warns me that it won't work (even though I know it will because your magic is running it as a page!)

My solution/suggestion would be a magic export called say `hoistablePageQuery` of https://github.com/ChristopherBiscardi/gatsby-mdx/blob/97f2fd9b3a47f3ca8f3be77ddcf76b69feca1bf1/packages/gatsby-mdx/component-with-mdx-scope.js#L53 would check for `hoistablePageQuery` inside of the exports and swap it over for pageQuery. That way your HOC has the pageQuery (so I get my query) and Gatsby doesn't care because `hoistablePageQuery` isn't a reserved Gatsby thing

I would submit a PR that does this but I cannot get gatsby-mdx running locally :( see my PR I made for another thing

Cheers,
Michael

**Comment by ChristopherBiscardi** [comment]
This is due to the HoC stuff we're doing behind the scenes, as you've discovered. There's a couple places where gatsby does checks that are focused on surfacing errors early for the 80% use case but that don't make sense when applied to the way we have to operate with mdx. There's no harm in the warning and it will be resolved at some point in the future when we figure out the best solution. gatsby-mdx is pre-1.0 so this warning isn't a top priority since it has no functional effects and is a gatsby heuristic that isn't applicable to this use case.

---

As for how we remove the warning, it's going to be an implementation detail. Our intention for the long-term is that the user shouldn't have to write special code for MDX to work (but could, if they had their own very advanced use case). I'm specifically not a fan of expanding the gatsby APIs here for a few reasons (such as what happens if gatsby introduces a `hoistablePageQuery`? but also more relevant is the user's need to memorize yet another API that would only work with MDX).

**Comment by falconmick** [comment]
Thanks

For now I will just know why the warning exists and ignore it.
