### ISSUE TITLE
pageQuery names collide when multiple wrappers hoist the same pageQuery

### ISSUE THREAD

**Issue by XHMM** [ChristopherBiscardi/gatsby-mdx#188]
**Describe the bug**
Always get the build error `GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLCompilerContext: Duplicate document named 'xxxx' ` using with `componentWithMDXScope` in `gatsby-node.js`

**To Reproduce**
A link to your [gatsby-mdx minimal repro](https://github.com/XHMM/gatsby-mdx-issue) and Steps to reproduce the behavior: please see readme

**Expected behavior**
no error
**Screenshots**
![image](https://user-images.githubusercontent.com/24786522/48151891-7a399f00-e2fd-11e8-849e-054031a344ab.png)

**Comment by ChristopherBiscardi** [comment]
Since we wrap your page in a higher order component and lift the pageQuery out and the pageQuery name doesn't (currently) get hashed when we do this, you can end up with multiple wrappers that include the same pageQuery. The solution is to remove the name of the query for now. In this case `BlogPostQuery`.

The real solution is to hash the pageQuery to prevent duplicate names when we lift it out in gatsby-mdx.

**Comment by XHMM** [comment]
I tries to remove the query name in `src/templates/article.tsx` , now code is below:
```
export const pageQuery = graphql`
  query{
    allMdx{
      ...
    }
  }
`
```
but now I get this warning, it became a non-page component, so weird.

![image](https://user-images.githubusercontent.com/24786522/48179780-bbf93280-e35b-11e8-8937-01ab608816b8.png)

**Comment by ChristopherBiscardi** [comment]
yes, the new warning you're seeing is expected for now. We hoist the pageQuery into the higher wrapper but we don't destructively touch the page component you wrote (so the pageQuery is still there even though it's not the "page component" anymore. The warning in our case is ignore-able with no ill effects. Basically the warning is a gatsby heuristic that doesn't apply because we're doing it intentionally.

I'm going to change the title of this and keep it open since the two things mentioned here (the query name hashing and the warning) are both things I'd like to get rid of, but it looks like you're good to go for now.

**Comment by XHMM** [comment]
Thanks for your explanation and waiting for your resolve 😁 

Now it seems that I cannot (or don't know how to) programmatically create pages  because this warning indicates query is not executed so I cannot get query data in my template file. I changed to create mdx pages in src/pages instead and wait for your following work.

**Comment by ChristopherBiscardi** [comment]
Closing this in favor of https://github.com/ChristopherBiscardi/gatsby-mdx/issues/203, which has a stronger use case.
