### ISSUE TITLE
gatsby-remark-autolink-headers options do not work

### ISSUE THREAD

**Issue by deltaskelta** [ChristopherBiscardi/gatsby-mdx#204]
**Describe the bug**

I can't seem to get any options from `gatsby-remark-autolink-headers` to work

I saw this [comment](https://github.com/ChristopherBiscardi/gatsby-mdx/pull/68#issuecomment-416760776) here but I didn't know how to interpret it. Are they expected to not work as it stands now?

**To Reproduce**
A link to your [gatsby-mdx minimal repro](https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro) and Steps to reproduce the behavior:
1. run the `custom-remark-plugins` example 
2. add following options to the gatsby-config.js`

```
          {
            resolve: "gatsby-remark-autolink-headers",
            options: {
              offsetY: `200`,
              icon: `<svg aria-hidden="true" height="20" version="1.1" viewBox="0 0 16 16" width="20"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg>`
            }
          },

```

**Expected behavior**

offset and icon should work as expected

**Comment by stevetweeddale** [comment]
Yeah, I don't think it's necessarily expected to work yet (see [this comment](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/10#issuecomment-416828641) from #10). I tried the other day and couldn't get it to work.

As a workaround, I whipped up [a custom component](https://github.com/Alfresco/builder-network/blob/1ff83d710b2095e3565e3498527ff2784fc0b52d/src/components/DocsHeading.js) to render H1-6's ([in the component map I'm passing into `MDXProvider`](https://github.com/Alfresco/builder-network/blob/1ff83d710b2095e3565e3498527ff2784fc0b52d/src/templates/mdx-documentation-page.js#L30-L35)) based on the code I say in that plugin. It's not super generic (my component is styled with tailwind classes rather than css-in-js) so it's not a drop in solution, but figured I'd post it here in case it's a helpful start for anyone. 

In fact, here's a slightly stripped back (entirely untested) version that might be a less noisy place to start from:

```js
import React from "react"
import { GoLink as LinkIcon } from "react-icons/go"
import SluggerContext from "components/SluggerContext"

const AutoLinkedHeading = ({ size: H, children, ...props }) => (
    <H {...props}>
      <SluggerContext.Consumer>
        {slugger => {
          const slug = slugger.slug(children)
          return (
            <a
              id={slug}
              href={`#${slug}`}
            >
              <LinkIcon size="16" />
            </a>
          )
        }}
      </SluggerContext.Consumer>
      {children}
    </H>
  )

export default AutoLinkedHeading
```

**Comment by deltaskelta** [comment]
I thought about doing exactly this but I stopped because I wanted to keep all the code in one place and I couldn't figure out which slugger gatsby-mdx was getting the slug from. (I didn't want to get burned by the slug having different rules and generating different slugs)

are you sure gatsby-mdx uses github slugger?

**Comment by ChristopherBiscardi** [comment]
I just rebuilt the gatsby-remark-* support in 0.3 (#190 is the PR if you're interested), so I'm going to leave this open until I can do some testing to see what's going on using the new version.

Generally speaking, it's almost always better to handle stuff like this in a component like @stevetweeddale if you can since you're already on MDX. The gatsby-remark-* plugins won't attach to JSX and they insert raw html right now instead of HAST which can cause some issues if you try to layer plugins, etc. The gatsby-remark-* plugins are "best effort" right now, although I'm hopeful that we'll have more complete support soon through a combination of PRs to the plugins and also the new code I just merged.

**Comment by stevetweeddale** [comment]
@deltaskelta yup, it [does indeed use Github slugger](https://github.com/gatsbyjs/gatsby/blob/e9e101c8c899d2a9ba827642c187279529355c33/packages/gatsby-remark-autolink-headers/src/index.js#L3)

I also wasn't sure if doing it in a component was worse or better, for example the remark transformer version doesn't seem to have to have to faff with a shared slugger instance as my component does - I _think_ that's because the remark plugins do their stuff at build time rather than render time, but I'm not sure).

@ChristopherBiscardi It's good to know that the component approach comes recommended! Are "MDX component plugins" _a thing_? eg. npm-installable drop in components that give you some feature? Should this be one?

**Comment by ChristopherBiscardi** [comment]
@stevetweeddale yeah, that's why we have the [`components`](https://github.com/ChristopherBiscardi/gatsby-mdx/tree/master/components) directory in this repo. I want things like "live code examples", etc to live there. Components that add functionality that was previously achieved using gatsby-remark AST manipulations would also fit in this category.

**Comment by stevetweeddale** [comment]
Sweet, good to know. OK, I guess I'll see if I can get around to wrapping that up into a PR then, so there's an out-of-the-box component to cover the gatsby-remark-autolink-headers functionality.

**Comment by RomanGotsiy** [comment]
@ChristopherBiscardi I was able to get it to work by changing `raw` hast node to mdast `html` node like below:

```js
node.children.unshift({
  type: `link`,
  url: `#${id}`,
  title: null,
  children: [
    {
      type: `html`,
      // The Octicon link icon is the default. But users can set their own icon via the "icon" option.
      value: icon,
    },
  ]
  data: {
    hProperties: {
      "aria-hidden": true,
      class: className,
    },
  },
})
```

I do the corresponding ast mutation in a custom mdast plugin as a workaround for now.

Looks like [`toJSX`](https://github.com/mdx-js/mdx/blob/b4ad28a5acdc7278473cddafdf8abb63cbc9debe/packages/mdx/mdx-hast-to-jsx.js#L50) function doesn't handle `raw` nodes at all. I don't fully understand why my approach works though but I hope it helps you to understand and fix the issue.

**Comment by stephanschubert** [comment]
@RomanGotsiy @ChristopherBiscardi This issues seems releated to https://github.com/ChristopherBiscardi/gatsby-mdx/issues/183 because I could "fix" it by keeping the `node.type` as `html` and setting `rawHTML` as `node.value` [here instead of setting `raw` and `hChildren`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-responsive-iframe/src/index.js#L64-L74).

GraphQL choked on [the `<style>` tag `gatsby-remark-embed-video` was inserting](https://github.com/borgfriend/gatsby-remark-embed-video/blob/master/src/EmbedVideo.js#L58-L65), so I had to use the `noIframeBorder` option.

N.B. `mdast-util-to-hast` [says](https://github.com/syntax-tree/mdast-util-to-hast#notes)

> Unknown nodes with children are transformed to div elements

But I am not sure I fully understand the implications...

**Comment by RomanGotsiy** [comment]
Actually, I just discovered an issue with my approach. By keeping `node.type` as `html` mdx ends up inlining the raw html tags into resulting JSX.

That's because plugins we use (embed-video and autolink-headers) inject `html` nodes into `mdxast` and **[MDX treats any inline html as JSX](https://github.com/mdx-js/specification#jsx)** by the spec.

 I'm not now sure what is a proper solution for this.

**Comment by stephanschubert** [comment]
@RomanGotsiy This probably explains why GraphQL choked:

```
The GraphQL query from ./src/pages/index.js failed.

Errors:
  unknown: Unexpected token, expected "}" (30:35)

    28 |             width: 100%;
    29 |             height: 100%;
  > 30 |           "><style>.foobar { border: 1px solid red; }</style></iframe>
       |                                    ^
    31 |           </div>
    32 |           </MDXTag></MDXTag>
    33 | <MDXTag name="p" components={components} parentName="li"><MDXTag name="inlineCode" components={components} parentName="p">{`youtube:DbgI7MdCqnU`}</MDXTag></MDXTag>

  GraphQL request (6:11)
  5:         childMdx {
  6:           excerpt(pruneLength: 250)
               ^
  7:           frontmatter {
```

**Comment by ChristopherBiscardi** [comment]
@RomanGotsiy The gatsby-remark plugins have to be changed to insert AST instead of html chunks because the html string chunks don't get processed later by the MDX pipeline.

**Comment by ChristopherBiscardi** [comment]
@RomanGotsiy you can read https://github.com/ChristopherBiscardi/gatsby-mdx/pull/190#issuecomment-446124409 for some background on the problem and some potential solutions.

> There is no MDAST representation of HTML nodes besides raw html node.

correct, except mdx uses MDXAST and adds additional nodes [such as `jsx` and `import`](https://github.com/mdx-js/mdx/blob/b4ad28a5acdc7278473cddafdf8abb63cbc9debe/packages/mdx/mdx-ast-to-mdx-hast.js) to handle JSX and imports, etc. Note that MDX files assume that any "html" you're writing is JSX so I wouldn't expect `class` to be transformed into `className` (MDX assumes you know you're writing JSX there so doesn't touch it).

The best option here may end up being core changes to move jsx node identification earlier in the pipeline and insert an html-to-jsx conversion process in the mdxast-to-hast handlers.

---

Curious as to what workarounds you're using if you wouldn't mind posting them.

**Comment by RomanGotsiy** [comment]
> Note that MDX files assume that any "html" you're writing is JSX so I wouldn't expect class to be transformed into className

That's what I was saying. MDX assumes HTML nodes to be JSX and plugins insert HTML nodes (plugins are not aware of mdx).

> The best option here may end up being core changes to move jsx node identification earlier in the pipeline and insert an html-to-jsx conversion process in the mdxast-to-hast handlers.

This looks like a viable solution. Alternatively, MDX can add support for `raw` nodes in mdx-hast-to-jsx. There is no good solution for this now as React requires a wrapper element for `dangerouslySetInnnerHTML`. But once [this or similar feature](https://github.com/facebook/react/issues/12014) lands in React it can be easily supported.

**Comment by RomanGotsiy** [comment]
I ended up detecting `html` nodes that are not `jsx` and wrapping them into `div` with `dangerouslySetInnnerHTML`.
E.g. here is a workaround for `gatsby-remark-prismjs` plugin which sets `lang` property on the `html` node:

```
visit(markdownAST, 'html', function(node) {
  if (node.type === 'html' && node.lang) {
    node.value = `<div dangerouslySetInnerHTML={{__html: ${JSON.stringify(node.value)}}} />`;
  }
});
```

I have a few like that for all the plugins that throw raw HTML

**Comment by stephanschubert** [comment]
@RomanGotsiy How do you detect whether a node is `html` and not `jsx`? On a case-by-case basis as shown here?

**Comment by RomanGotsiy** [comment]
@stephanschubert yes, exactly. Handles only my specific use case.

**Comment by zslabs** [comment]
> @RomanGotsiy The gatsby-remark plugins have to be changed to insert AST instead of html chunks because the html string chunks don't get processed later by the MDX pipeline.

Could that potentially be why attempting to use `gatsby-remark-prismjs` with a block-level snippet like:

```js
console.log('test')
```

produces the following?

```
error UNHANDLED REJECTION


  SyntaxError: unknown: Unexpected token (38:189)
    36 | <MDXTag name="p" components={components}>{`To help us decipher components that are being impa  cted by a specific breakpoint, we use the `}<code class="language-text">@</code  >{` symbol attached to our classnames, like so: `}<code class="language-text">.colum  n-6@medium</code>{`. This translates to a six-column element that only inherits those styles on the medi  um breakpoint. We did this to avoid cases where: `}<code class="language-text">.button--large  [33m</code>{` could be confused for a breakpoint instead of a size modifier.`}</MDXTag>
    37 | <MDXTag name="p" components={components}><MDXTag name="strong"  [39m components={components} parentName="p">{`Note:`}</MDXTag>{` When writing your o  wn breakpoint modifiers, remember to escape the `}<code class="language-text">@</  3mcode>{` symbol. You can reference these classes without escaping within your HTML.`}</MDXTag>
  > 38 | <div class="gatsby-highlight" data-language="scss">  9m<pre class="language-scss"><code class="language-scss">  33m<span class="token selector">.myComponent </span><span  39m class="token punctuation">{</span>
       |                                                                                                                                                                                                ^
    39 |   <span class="token property">width</span><  mspan class="token punctuation">:</span> 200px<span   36mclass="token punctuation">;</span>
    40 |
    41 |   &amp;\<span class="token atrule"><  3mspan class="token rule">@medium</span></span>  39m <span class="token punctuation">{</span>

  - index.js:4028 _class.raise
    [chaoskit]/[@babel]/parser/lib/index.js:4028:15

  - index.js:5343 _class.unexpected
    [chaoskit]/[@babel]/parser/lib/index.js:5343:16

  - index.js:3504 _class.jsxParseIdentifier
    [chaoskit]/[@babel]/parser/lib/index.js:3504:14

  - index.js:3514 _class.jsxParseNamespacedName
    [chaoskit]/[@babel]/parser/lib/index.js:3514:23

  - index.js:3525 _class.jsxParseElementName
    [chaoskit]/[@babel]/parser/lib/index.js:3525:23

  - index.js:3610 _class.jsxParseOpeningElementAt
    [chaoskit]/[@babel]/parser/lib/index.js:3610:24

  - index.js:3643 _class.jsxParseElementAt
    [chaoskit]/[@babel]/parser/lib/index.js:3643:33

  - index.js:3712 _class.jsxParseElement
    [chaoskit]/[@babel]/parser/lib/index.js:3712:19

  - index.js:3719 _class.parseExprAtom
    [chaoskit]/[@babel]/parser/lib/index.js:3719:21

  - index.js:6019 _class.parseExprSubscripts
    [chaoskit]/[@babel]/parser/lib/index.js:6019:21

  - index.js:5998 _class.parseMaybeUnary
    [chaoskit]/[@babel]/parser/lib/index.js:5998:21

  - index.js:5907 _class.parseExprOps
    [chaoskit]/[@babel]/parser/lib/index.js:5907:21

  - index.js:5879 _class.parseMaybeConditional
    [chaoskit]/[@babel]/parser/lib/index.js:5879:21

  - index.js:5826 _class.parseMaybeAssign
    [chaoskit]/[@babel]/parser/lib/index.js:5826:21

  - index.js:5779 _class.parseExpression
    [chaoskit]/[@babel]/parser/lib/index.js:5779:21

  - index.js:3580 _class.jsxParseExpressionContainer
    [chaoskit]/[@babel]/parser/lib/index.js:3580:32


error Command failed with exit code 1.
```

Version `0.2.0` works fine, but upgrading to `0.3.5` causes the above error.

### Config

```
{
      resolve: 'gatsby-mdx',
      options: {
        defaultLayouts: {
          default: require.resolve('./src/templates/Article.js'),
        },
        gatsbyRemarkPlugins: [
          {
            resolve: 'gatsby-remark-autolink-headers',
          },
          {
            resolve: 'gatsby-remark-prismjs',
          },
        ],
      },
    }
```

**Comment by ChristopherBiscardi** [comment]
version 0.2.0 included a heavy-handed approach that tried to convert all html injected by gatsby-remark plugins to JSX. This plugin caused other bugs in the way core MDX behaved, so in 0.3.x it was removed in favor of fixing the problems in the plugins themselves rather than trying to patch over them and creating different issues.

I'm also in the process of building out a set of components that can replace these kinds of plugins ([prism example](https://www.christopherbiscardi.com/post/codeblocks,-mdx,-and-mdx-utils) and [initial spike for autolink-headers](https://github.com/ChristopherBiscardi/gatsby-mdx/tree/b1657ae41bd04db4beea814a09cfb0cf23c1b774/packages/mdx-component-autolink-header)) since components provide a more powerful model in MDX when compared to remark (which can only use AST transformations).

**Comment by vpicone** [comment]
If you supply your own components to the MDX provider, make sure you're passing along additional props. This was preventing my ID from being applied:

```jsx
const H2 = ({ children, ...rest }) => (
  <h2 css={h2Css} className="carbon--mdx__h2" {...rest}>
    {children}
  </h2>
);
```

vs

```jsx
const H2 = ({ children, ...rest }) => (
  <h2 css={h2Css} className="carbon--mdx__h2" {...rest}>
    {children}
  </h2>
);
```

**Comment by ChristopherBiscardi** [comment]
> how would those solutions handle something like a using bold text in a header? The children get split up and the bold text becomes a react component.

Not sure what you're asking here, maybe an example would help illustrate it? It sounds like you want to apply a `font-weight` to the `h2` tag.

If you mean something like 

```markdown
## **Some Bold Heading**
```

then you end up with something like this, and you can `MDXProvider` the `strong` tag which will have a prop to tell you if it's parent is an `h1`. 

```html
<h2>
  <strong>Hello, world!</strong>
</h2>
```

**Comment by vpicone** [comment]
My issue was when only one of the words was bolded, `props.children` is no longer a string but an array at that point.

**Comment by janosh** [comment]
I'm seeing missing styles on the anchor after moving from remark to MDX. Specifically, the `margin-left: -20px;` is not being attached, resulting in headings with a small left indent. Has anyone else experienced this issue and found a fix?

![missing-styles](https://user-images.githubusercontent.com/30958850/64434405-6515d400-d0b8-11e9-9589-2a2ec5c2f74c.png)
