### ISSUE TITLE
How to pass "dynamic" data to component in mdx body?

### ISSUE THREAD

**Issue by snawbel** [ChristopherBiscardi/gatsby-mdx#238]
A sample "work" .mdx file looks like this:

```mdx
---
title: My Work
tags: [foo, bar]
---
I did this! And I've blogged about it:

<RelatedBlogPosts />

Pretty good, huh?
```

How would I go about to have `<RelatedBlogPosts />` render a list of blog posts that depends on the tags of the current work?

I can query for and fetch the related posts in the work template, but how can I pass this data to the `<RelatedBlogPosts />` component inside the mdx body?

I tried using MDXRenderer's `scope` prop but this seems to only work for components that don't depend on non-static data.

(Bonus: Even sweeter would be to be able to do `<RelatedBlogPosts tags={['foo']} />`.)

**Comment by ChristopherBiscardi** [comment]
We're thinking about some APIs that will allow `<RelatedBlogPosts tags={['foo']} />` if it can be expressed as a `StaticQuery` but have not made it very far yet. It's likely a "post-1.0" thing where I'm hoping 1.0 happens around the end of January. https://github.com/gatsbyjs/gatsby/issues/10482 is a related issue you may want to watch for that.

# MDX files in src/pages

If you're using an MDX file in `src/pages`, you can write a page query in the MDX file and the data will be available in props. There's an example in the [kitchen-sink](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/8cacf7eec8f91fbd60cd1f3abc462282f8948669/examples/kitchen-sink/src/pages/basic-page-query.mdx) which is [continuously deployed](https://gatsby-mdx-kitchen-sink.netlify.com/basic-page-query/)

```js
import { graphql } from 'gatsby';

export default ({children, ...props}) => (
  <div className="my custom layout">
    <div>{children}</div>
    <pre>{JSON.stringify(props, null, 2)}</pre>
  </div>
)

export const pageQuery = graphql`
query BasicWithQuery {
    allSitePage {
      edges {
        node {
          path
        }
      }
    }
  }
`
```

Since props are available as `props.key` in the MDX file you could write a component that took the result of your page query for tags.

```js
# Some file

<RelatedBlogPosts relatedPosts={props.data.related} />

export const query = graphql`...`
```

# A title

Some content
```

# Programmatically generated content

Alternatively, if you're using `MDXRenderer` you can pass any data you want in as a prop and it will be forwarded into the MDX content. So your template can do the same query as above and pass it into your content.

```js
<MDXRenderer relatedPosts={props.data.related} />
```

**Comment by snawbel** [comment]
Thanks! This is really helpful.

**Comment by johno** [comment]
Closing since this is now documented and the StaticQuery issue is being tracked in https://github.com/gatsbyjs/gatsby/issues/10482
