### ISSUE TITLE
Ability to opt out of automatic src/pages page creation

### ISSUE THREAD

**Issue by alirussell** [ChristopherBiscardi/gatsby-mdx#243]
**Describe the bug**
There seem to be a number of issues that talk about using MDXRenderer or globalScope (which I think is currently not working properly), but I cant seem to get my app built using `gatsby build`, even though it works in development.

I have a number of markdown files which I use custom TabGroup/Tab components in.  Im rendering these using a Gatsby template, and the following MDX Renderer code:

```
  render() {
    const { cn, body, scope } = this.props;
    return (
      <div id="article-content">
        <MDXRenderer scope={{ TabGroup, Tab, ...scope }} components={{...components}}>{body}</MDXRenderer>
      </div>
    );
  }
```

This works when using `gatsby develop`, but I get `WebpackError: ReferenceError: TabGroup is not defined` when I do `gatsby build`.

I have a lot of different markdown files, so I don't want to have to import the TabGroup component in each of them, so was wondering why this works in development, but not when I try and build for production?

I tried using `globalScope`, but looking at the code for that, it doesn't seem like it does anything other than write a `global-scope.js` file, and I cant see how that file is used?

Any help would be appreciated...!

Thanks

**Comment by ChristopherBiscardi** [comment]
> I tried using globalScope, but looking at the code for that, it doesn't seem like it does anything other than write a global-scope.js file, and I cant see how that file is used?

`globalScope` hitches a ride on the scope functionality we use to provider all MDX files with their scope. After the `globalScope` gets written out, it gets scooped up into [a `wrapRootElement` call](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/cea5dc6c13ff8f9b882a8a11fd0533d06f554cbd/packages/gatsby-mdx/wrap-root-element.js) and provider to `MDXRenderer` via context.

---

It's pretty hard to figure out what you're running into without a [reproduction](https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro/blob/master/package.json)

**Comment by alirussell** [comment]
Thanks @ChristopherBiscardi, that makes sense now.

Sorry, I was trying to get a reproducible example, as my main app is actually quite large and complex, so had to pick out the parts to mimic the situation.

Here is the repo: https://github.com/alirussell/my-mdx-starter

I think I have narrowed part of the error down.  From the repo you will notice that I have gone down more of a custom Gatsby template route, because thats how the app was before I started trying to migrate to MDX..

My app is not perhaps a standard app setup.  I don't use the `defaultLayouts` config parameter to define a layout to handle the different markdown files, I create custom pages with a path based on the source .md files in https://github.com/alirussell/my-mdx-starter/blob/master/gatsby-node.js. These pages use a standard Gatsby template (https://github.com/alirussell/my-mdx-starter/blob/master/src/templates/test.js) which uses `MDXRenderer` to provide the `TabGroup` component.

The issue I have now realised, is that at runtime this is fine and I can view the custom page (at `/custom/test`), but it fails at build time because `gatsby-mdx` is still reading the `pages/test.md` file and also trying to create a page under the path `/test`.  This standard page is not using `MDXRenderer` and therefore doesn't have access to my custom scope.

Ideally I want to stop `gatsby-mdx` from also creating pages? 

If thats not possible, in the example repo I have tried to also define a `defaultLayouts` parameter with a layout, but this doesn't work.  Ive tried using `MDXRenderer` in this layout and Ive also tried setting the `globalScope` to import my component, but both methods still error with the missing TabGroup component.

Any idea?

**Comment by ChristopherBiscardi** [comment]
you hit #239 by putting your .md files in src/pages. gatsby-mdx includes support for the internal gatsby-plugin-page-creator that handles these.

I suppose we could add a way to "opt out" of the page creation in src/pages. it would make migrating from remark easier for people who are using src/pages but bypassing the page creator. I can't think of a way to automatically detect if a page was created at that path. People need source-filesystem on src/pages for image support so we can't rely on that as a signal and page-creator will create pages no matter what since it exists outside of the gatsby node system. 

```js
options: {
}
```

**Comment by damassi** [comment]
Rather than `autoCreateSrcPages` being written to support globalScope, how feasible would it be to augment the current page behavior to support it? Just hit this issue too.

**Comment by ChristopherBiscardi** [comment]
Very feasible. Since the global scope is currently implemented as [a specific file](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/b1657ae41bd04db4beea814a09cfb0cf23c1b774/packages/gatsby-mdx/gatsby-node.js#L56) located at `.cache/gatsby-mdx/mdx-scopes/global-scope.js`, we need the [resulting code in the webpack loader](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/b1657ae41bd04db4beea814a09cfb0cf23c1b774/packages/gatsby-mdx/loaders/mdx-loader.js#L176-L181) to also import the global-scope file (in addition to `React` and `MDXTag`) and destructure the imports so that they're available to the rest of the file.

I'm not sure what the best way to get the list of exported names is, but I think it could be a good option to write a simple babel plugin to grab the names exported from the global scope file, then run the plugin on that file to grab the names in the mdx-loader and use that list to do the destructuring.

I'm happy to answer any questions you have about it @damassi

**Comment by ChristopherBiscardi** [comment]
We'll also want to add a dependency in the webpack loader on the global scope file but I kinda forget how to do that (`this.addDependency` maybe?) and it's not as important as getting it working in the first place.

**Comment by damassi** [comment]
Cool, I'll give this a look on Monday 👍

**Comment by ChristopherBiscardi** [comment]
`globalScope` is now supported through using `MDXProvider` in mdx-js/mdx 1.0.
