### ISSUE TITLE
mdx plugin is not working graphql query

### ISSUE THREAD

**Issue by youngboy** [ChristopherBiscardi/gatsby-mdx#25]
I am testing with remark-toc plugin, 

by using this lib it is works well for direct import

```
   // gatsby-config.js
    const toc = require('remark-toc')
    ...
    {
      resolve: `gatsby-mdx`,
      options: {
        mdPlugins: [toc],
      }
    },
    ...
```

but query graphql code showing that TOC(table of content) plugin is not working correctly.

I think bug is in `gatsby-node` https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/packages/gatsby-mdx/gatsby-node.js#L28

here you guys forgot pass options for parsing ? but for `mdx-loader` it is works find.

**Comment by youngboy** [comment]
also it would be nice to add graphql field for TOC render as jsx code here😅or maybe let another plugin do it ?

**Comment by avigoldman** [comment]
Thanks for reporting! We need to have parity between the `mdx-loader` and the `code` field in GraphQL. It also doesn't handle the default layout correctly.

We plan on have supporting for a TOC GraphQL field. (#1)

Out of curiosity, how are you using the `code` GraphQL field?

**Comment by youngboy** [comment]
I didn't use code field yet, just testing around :) . In fact, I don't know how to use it so far, maybe it is for the case of `createPage` component by `require-from-string` ?

**Comment by ChristopherBiscardi** [comment]
@youngboy the `code` graphql field is really only for very advanced use cases right now. In the general case for creating pages, you probably want to use the `fileAbsolutePath` in the component key like this example. That allows you to (implicitly) pass the mdx file through the webpack loader, etc without having to worry about transforming the raw code with babel, etc yourself.

```js
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;
  return new Promise((resolve, reject) => {
    resolve(
      graphql(
        `
          {
            allMdx {
              edges {
                node {
                  relativePath
                  fileAbsolutePath
                  fileNode {
                    name
                  }
                }
              }
            }
          }
        `
      ).then(result => {
        if (result.errors) {
          console.log(result.errors);
          reject(result.errors);
        }

        // Create pages.
        result.data.allMdx.edges.forEach(({ node }) => {
          createPage({
            path: `/non-page/${node.fileNode.name}`,
            component: node.fileAbsolutePath,
            context: { absPath: node.absolutePath }
          });
        });
      })
    );
  });
};
```


The mdx file itself can have queries through a `pageQuery` export or `<StaticQuery/>` component which should solve most problems :) If it turns out you really do want to use the code field, let us know because we're looking for potential use cases in #13

**Comment by youngboy** [comment]
Always confusing about `component: node.fileAbsolutePath`, totally understand now.  

Thanks for detail explanation @ChristopherBiscardi
