### ISSUE TITLE
Add error message if the webpack config is empty when trying to query `html`

### ISSUE THREAD

**Issue by JamesMessinger** [ChristopherBiscardi/gatsby-mdx#250]
I'm trying to use gatsby-mdx on my project, but I keep getting this error when I run `gatsby develop` or `gatsby build`:

```
The GraphQL query from C:/my project/src/templates/blog-post.jsx failed.

Errors:
  Cannot read property 'push' of undefined

  GraphQL request (5:5)
  4:   mdx(fileAbsolutePath: {eq: $foo}) {
  5:     html
         ^
  6:     frontmatter {
```

This looks awfully similar to [this error in Issue #223](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/223#issuecomment-452480877), so maybe it only occurs when using gatsby-mdx on files outside of the `src/pages/` directory.  (that's what I'm doing too).

After deep-diving into the code, I ultimately traced it down to this line:

https://github.com/ChristopherBiscardi/gatsby-mdx/blob/644b41841d91f38884f7722d6239d3b8cef75762/packages/gatsby-mdx/utils/render-html.js#L15

Apparently `webpackConfig.plugins` is sometimes `undefined`, which causes the error.  So I tried to fix it by setting `webpackConfig.plugins` to an empty array if it's `undefined`:

```
webpackConfig.plugins = webpackConfig.plugins || [];
webpackConfig.plugins.push(
```

But that just caused other errors, because there are plugins missing, so JSX can't be compiled.  So I'm stuck.  Not sure how to fix the problem.

Oh... and here's another strange thing....  When I run `gatsby develop`, I get the error that I mentioned above, but the dev server still starts up.  If I try to browse to one of my .mdx pages, it doesn't render correctly.  BUT, if I make **any** change to the GraphQL query and save the file, it causes the `gatsby-mdx` plugin to run again, and **this time it works**!  The page renders fine after that.   But, of course, if I stop the server, then the next time I start it, the same problem will start all over again.

**Comment by ChristopherBiscardi** [comment]
What's your use case for using `html`? It looks like you're using it before the webpack config is compiled so would *probably* be better off using `code.body` and `MDXRenderer`.

**Comment by JamesMessinger** [comment]
@ChristopherBiscardi - Thansk for the tip!  I was converting from the Gatsby Remark plugin to the MDX plugin, so my query with `html` was leftover from the old Remark code. Changing it to `code.body` did the trick.  👍 

Thins brings up two questions though:

*1)*  Why expose an `html` field at all if it causes runtime errors and shouldn't be used anyway?  It makes it easy for other people to make the same mistake as me.

*2)* If there's a reason for the `html` field to stay, then could you print some warning text and/or throw a more informative error?  It took me forever to track down what was causing `Cannot read property 'push' of undefined` .

**Comment by ChristopherBiscardi** [comment]
1) `html` is for supporting [gatsby-plugin-feed](https://github.com/gatsbyjs/gatsby/tree/416a216bee042f77dc4bde1662d866501cdbb43d/packages/gatsby-plugin-feed) so people can ship RSS feeds. At the time the feed plugin makes the graphql request, the webpack config has already been constructed so there's no issue. Using `html` in application-level code causes an issue because the webpack code hasn't been constructed by the time most queries are run by gatsby. There's an attempt to use [html for the tableOfContents](#236) but it's currently unclear how far that can go and if it will end up working. In any case, it will be always be slower and more error prone than querying `code.body` due the the extra machinery that needs to happen.

2) yeah, we should do this. I'd accept a PR for it. I avoided implementing `html` for a long time because it's one of the "remark-isms" that is there because of the way the assumptions remark makes about the world and doesn't make sense if you're using MDX.

**Comment by ChristopherBiscardi** [comment]
for the good first issue label:

We could throw an error through the gatsby `reporter` here: https://github.com/ChristopherBiscardi/gatsby-mdx/blob/644b41841d91f38884f7722d6239d3b8cef75762/packages/gatsby-mdx/utils/render-html.js#L7

or in `html` here: https://github.com/ChristopherBiscardi/gatsby-mdx/blob/644b41841d91f38884f7722d6239d3b8cef75762/packages/gatsby-mdx/gatsby/extend-node-type.js#L189 since the issue is mostly for the `html` field
