### ISSUE TITLE
React components in `excerpt` are not rendered

### ISSUE THREAD

**Issue by stephanschubert** [ChristopherBiscardi/gatsby-mdx#256]
**Describe the bug**

React components aren't rendered when resolving `excerpt` fields.

```xml
// from public/rss.xml
<item>...<description><![CDATA[<Notes.Experiment /> ...
```

**To Reproduce**

See https://github.com/ChristopherBiscardi/gatsby-mdx/issues/249, but full plugin configuration:

```js
    {
      options: {
        feeds: [
          {
            output: `rss.xml`,
            query: `
            {
              allMdx(
                filter: { fileAbsolutePath: { regex: "//posts//" } }
                limit: 1000,
                sort: { order: DESC, fields: [frontmatter___date] }
              ) {
                edges {
                  node {
                    frontmatter {
                      title
                      date
                    }
                    fields {
                      slug
                    }
                    excerpt
                    html
                  }
                }
              }
            }
           `,
            serialize: ({ query: { site, allMdx } }) => {
              return allMdx.edges.map(edge => {
                return {
                  ...edge.node.frontmatter,
                  custom_elements: [{ "content:encoded": edge.node.html }],
                  description: edge.node.excerpt,
                  guid: site.siteMetadata.siteUrl + edge.node.fields.slug,
                  url: site.siteMetadata.siteUrl + edge.node.fields.slug,
                };
              });
            },
          },
        ],
        query: `
        {
          site {
            siteMetadata {
              title
              description
              siteUrl: url
            }
          }
        }
      `,
      },
      resolve: `gatsby-plugin-feed`,
    },
```

**Expected behavior**

React components should be rendered.

**Comment by szarouski** [comment]
@stephanschubert sorry I have an unrelated question which I can't figure out and I wonder if you can spend 3 minutes to help me. I see that default configuration in gatsby-mdx/feed is using
```
                    fields {
                      slug
                    }
```
and I see in your example that at least you don't get an error. If I manually run same query from feed.js file but with fields section commented out, it works, but otherwise it fails because I don't even have that property at all, so I get `Cannot query field "fields" on type "Mdx".`

I wonder if you might know where this data should be set (maybe it should be defined in .mdx file) or if you don't know maybe you can run a query in http://localhost:8000/___graphql and see what it is returning. 

I would really appreciate any help!

**Comment by ChristopherBiscardi** [comment]
@szarouski `fields` is the key that generated fields go in

You can find an example of generating a slug field [in the kitchen-sink example](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/ffdfd4cbdfa3a060f6c2a2f0da3be1351811d97b/examples/kitchen-sink/gatsby-node.js#L65-L76) and the gatsby documentation for node and field creation [here](https://www.gatsbyjs.org/docs/node-creation/#changing-a-nodes-fields).
