### ISSUE TITLE
Throws an error on this specific code block when used with `rehype-prism`

### ISSUE THREAD

**Issue by ahmedelgabri** [ChristopherBiscardi/gatsby-mdx#262]
**Describe the bug**
After updating to `0.3.5` this specific code block is throwing an error https://github.com/ahmedelgabri/gatsby-mdx-minimal-repro/commit/47f2daa8fdfd9c0d44d9bf1e4d61c262cca5d775#diff-522b7407e210088f3588b943aec44115

if I remove the language (`vim`) from the code block it works fine though, all other code blocks are working fine, also any other `vim` code block works fine

**To Reproduce**
A link to your [gatsby-mdx minimal repro](https://github.com/ahmedelgabri/gatsby-mdx-minimal-repro) and Steps to reproduce the behavior:
1. Run `yarn develop`
2. See the error

**Expected behavior**
Build to pass & code to be highlighted

**Comment by ChristopherBiscardi** [comment]
Did you happen to update to `0.3.x` from `0.2.0`?

**Comment by ahmedelgabri** [comment]
Yes, this is the main repo that I'm trying to update https://github.com/ahmedelgabri/gabri.me/commit/58387dd719bd82a626f9230ccad7623d7463b4c1

**Comment by ahmedelgabri** [comment]
@ChristopherBiscardi 	any updates?

**Comment by ChristopherBiscardi** [comment]
@ahmedelgabri Working on a drop-in replacement for gatsby-remark-prismjs that uses a component based on prism-react-renderer instead of AST manipulation in https://github.com/ChristopherBiscardi/gatsby-mdx/pull/274. Also working on some fixes upstream that could potentially fix the problems you're seeing with the rehype-prism plugin in https://github.com/mdx-js/mdx/pull/366. 

Generally I'd suggest not using AST plugins for syntax highlighting and using an approach based on MDXProvider and components such as described here -- https://www.christopherbiscardi.com/post/codeblocks-mdx-and-mdx-utils

**Comment by ChristopherBiscardi** [comment]
fixed in `@mdx-js/mdx@0.19`

**Comment by ahmedelgabri** [comment]
@ChristopherBiscardi thanks! one last question, after this update I'm getting errors from a different code block. It fails because of the inner backticks, I tried to do multiple things:

- Use more than one backtick
- Using tildas for the main codeblock 

None is working, so how can I use backticks inide codeblocks?

~~~
foo `bar`
~~~

**Comment by ChristopherBiscardi** [comment]
@ahmedelgabri  there's a bug being tracked here for this: https://github.com/mdx-js/mdx/issues/430

There's always an @mdx-js/mdx v0.20 release with more improvements to escaping and the gatsby-remark-* ecosystem
