### ISSUE TITLE
Adding file times to MDX

### ISSUE THREAD

**Issue by jasonbahl** [ChristopherBiscardi/gatsby-mdx#264]
**Is your feature request related to a problem? Please describe.**
When querying for MDX files the `birthTime` and `modifiedTime` are not available like they are when querying for files.

**Describe the solution you'd like**
When querying for MDX files, I would like to be able to access the `birthTime` and `modifiedTime` in the same way I do when querying for a file. 

For example, I can query files like so: 

```
{
  allFile {
    edges {
      node {
        id
        birthTime
        changeTime
      }
    }
  }
}
```

But when querying for MDX, the `birthTime` and `changeTime` fields are not available. 

**Describe alternatives you've considered**
I've considered trying to add a node field via `onCreateNode`, similar to how you show to add the `slug` field here: https://gatsby-mdx.netlify.com/guides/programmatically-creating-pages

I've also just considered using a `file` query to get the data, but seems like something that _should_ be exposed on MDX already?

**Comment by jasonbahl** [comment]
Actually, I'm not sure these times do what I was expecting them to do. I was hoping one of the timestamps would actually be the created time, and one be the updated time, but when I use a file query, all the times come back as the most recently modified time. 

Maybe I just need to add some fields to manually be updated in my FrontMatter? 🤔 

You can close this, unless you think it's a valid issue to address still. I think for my needs, I'll just add some frontMatter fields.

**Comment by ChristopherBiscardi** [comment]
For the record, you can access the file node associated with an MDX node with an inline fragment. The inline fragment means "if the parent is a `File`, get the `birthTime`.

```graphql
{
  allMdx {
    edges {
      node {
        id
        parent {
          ... on File {
            birthTime
          }
        }
      }
    }
  }
}
```

**Comment by ChristopherBiscardi** [comment]
I'm not sure what you were trying to use birthtime for, but it's effectively returned by the system's [stat](https://en.wikipedia.org/wiki/Stat_(system_call)) syscall because the filesystem source [calls fs.stat](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-file-node.js#L27) to get the data.

`stat` will give you the time at which you cloned the repo, not the time at which the file was created. If you're using git you would be able to get the date at which the file was added using 

```shell
git log --format=%aD package.json | tail -1
```

I *think* there are ways to query that data through gatsby's graphql layer but I haven't used them. Personally I use a created at `date` in my frontmatter.

**Comment by jasonbahl** [comment]
Ya, I was hoping to get the time the file was created, but I think frontMatter makes more sense for my needs. 

Thanks for the info on the parent field.

Really liking MDX in Gatsby! Great work!
