### ISSUE TITLE
apply wrapRootElement lifecycle APIs when rendering html

### ISSUE THREAD

**Issue by mmmaaatttttt** [ChristopherBiscardi/gatsby-mdx#286]
**Is your feature request related to a problem? Please describe.**

Currently my builds are breaking because of a combination of `gatsby-mdx`, `gatsby-plugin-feed`, and `redux`. 

Redux integration requires me to make use of `wrapRootElement` (basically what Gatsby suggests [here](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redux)). But the `feed.js` file in `gatsby-mdx` which is used to provide options to `gatsby-plugin-feed` contains a query involving `html`.

Since this html rendering circumvents `wrapRootElement`, my build is crashing with errors about not being able to find a redux `store` for components that are trying to connect to redux.

**Describe the solution you'd like**

I'd like to be able to use all three of the aforementioned tools and have the builds work. I think this would involve making sure that querying for `html` would apply certain Gatsby lifecycle APIs (specifically in my scenario, `wrapRootElement`).

**Describe alternatives you've considered**

Aside from just not using the feed plugin, I'm not sure.

**Additional context**

See [this](https://twitter.com/mmmaaatttttt/status/1094386372503265280) Twitter thread.

I have no sense for how straightforward or challenging such a feature would be, but if someone can help provide me a better intuition I'm happy to try to send over a PR myself. FYI, the repository I'm working on is here: https://github.com/mmmaaatttttt/personal-site

Thanks! 👋

**Comment by ChristopherBiscardi** [comment]
So [the webpack config](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/ffdfd4cbdfa3a060f6c2a2f0da3be1351811d97b/packages/gatsby-mdx/utils/render-html.js) that gatsby generates in the actual site build is reused to render the MDX code body as HTML. The webpack entry is replaced so that it's [this file](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/ffdfd4cbdfa3a060f6c2a2f0da3be1351811d97b/packages/gatsby-mdx/utils/wrap-root-render-html-entry.js), which handles importing the scope via a special webpack loader and hooking up the MDXRenderer. What we'll need to do is wrap the `MDXRenderer` in the entry file with the result of the `wrapRootElement`s that exist in various plugins. (and really `wrapPageElement` but we can probably leave the page API for later).

At the very least, the redux store will have the list of plugins (and I think which APIs are implemented by which plugin) and we can use that list to run each `wrapRootElement` to wrap the entry's `MDXRenderer`. There might be a more straightforward way to do this (like maybe patching directly into using the [apiRunner](https://github.com/gatsbyjs/gatsby/blob/5adb2a3beb10ff9ca9fd58b351d8e6bbb0dd05a1/packages/gatsby/src/utils/api-runner-node.js)), but at the least this should work. I think this should be straightforward since iirc the plugins list in redux contains the full file path to each plugin, so it's really a matter of getting that list into the webpack entry (probably using a global like we do for the MDXContent) and then requiring the plugins + `/gatsby-ssr.js` and running them if they have a `wrapRootElement` defined in `gatsby-ssr`.

If you want to try to get this done I'm happy to answer any questions you have :)

---

In the meantime, you can also replace the `html` with the `excerpt` in the rss feed plugin if you want. It's not a real replacement, but would at least send out a feed entry for every blog post so if people wanted to read they could click through to the post.

**Comment by mmmaaatttttt** [comment]
Sure, that makes sense. Identifying plugins that implement `wrapRootElement` is relatively straightforward, here's a diff that makes the relevant plugin paths globally available: https://github.com/ChristopherBiscardi/gatsby-mdx/compare/master...mmmaaatttttt:master

In terms of running the relevant plugins, do you think it makes more sense to try to do that from within the webpack entry, or would it be better to offload that to a separate loader? (I haven't had to do too much tinkering with webpack so I'm a little unsure here.)

**Comment by ChristopherBiscardi** [comment]
I [opened a PR from your branch](https://github.com/ChristopherBiscardi/gatsby-mdx/pull/289) so we can talk there.

For running the plugins, I think it makes the most sense to do it in the entry for now. In a future update, we might be able to do something fancier to optimize and only run them all once instead of on every `html` query but I'm not concerned about that now.

**Comment by mmmaaatttttt** [comment]
(fixed by #289)
