### ISSUE TITLE
SyntaxError on build when project contains gatsby-transformer-react-docgen

### ISSUE THREAD

**Issue by jschuler** [ChristopherBiscardi/gatsby-mdx#288]
**Describe the bug**
Hi, really liking this project! My issue is that I have various *.js files with comments such as:
`/** Additional props are spread to the container <div> */`

I am including gatsby-transformer-react-docgen which parses them and internally creates markdown nodes. It appears that gatsby-mdx picks these up and then complains that the tag is not closed:
<img width="1132" alt="screen shot 2019-02-12 at 9 47 50 am" src="https://user-images.githubusercontent.com/869106/52643550-49907500-2eab-11e9-9cf5-c219e000bf07.png">

Here is the content of one such node that was picked up in the on-create-node.js file:
```
{"id":"afbf1867-a9a0-552f-979f-a085609bfa73","parent":"c0d4de61-2ee8-591b-83c0-3437378bf858","children":[],"text":"Additional props are spread to the container <div>","internal":{"type":"ComponentDescription","mediaType":"text/markdown","content":"Additional props are spread to the container <div>","contentDigest":"0c8890eb274dee916fbcffb5c0edb93e","owner":"gatsby-transformer-react-docgen"}}
```

**To Reproduce**
https://github.com/jschuler/gatsby-mdx-minimal-repro/pull/1
1. I added prop-types and one of the prop comments has an unclosed tag
2. I make my components folder searchable by gatsby with gatsby-source-filesystem in gatsby-config.js
3. I added gatsby-transformer-react-docgen to gatsby-config.js
4. On build, i get a similar error as above

**Expected behavior**
gatsby-mdx should not pick up nodes created by gatsby-transformer-react-docgen

**Comment by ChristopherBiscardi** [comment]
Yes, this is expected because the markdown in the comment is malformatted and will result in the browser correcting the unclosed `<div>` in whatever way it sees fit (usually, it will wrap all of the rest of the content in a `div` which results in an arbitrary line-break because of the div's block formatting). You should be able to fix the markdown by inserting inline code markers as such:

    /** Additional props are spread to the container `<div>` */

> gatsby-mdx should not pick up nodes created by gatsby-transformer-react-docgen

Can you tell me more about what you're trying to do here? gatsby-mdx (and the remark transformer, etc) operate on nodes with the markdown media-type so the way to get it to not parse as markdown would be to prevent react-docgen from generating nodes with the markdown media-type. Are you wanting to use the comment text directly without markdown support?

**Comment by jschuler** [comment]
> Are you wanting to use the comment text directly without markdown support?
Yes exactly, in this case I am grabbing prop comments via gatsby-transformer-react-docgen and just outputting the string into a table to display the component API. I don't need full markdown capabilities for these nodes. 
If I can avoid it I'd prefer to not have to edit all the comments in the upstream project, IMO it is okay for comments to have invalid/pseudo code or unclosed tags.

A quick workaround I added was the addition of this in on-create-node.js:
```
if (node.internal.owner === "gatsby-transformer-react-docgen") {
    return;
  }
```
Not sure if there is a better way to do it :) Maybe gatsby-mdx could have an ignore option that ignores markdown created by specific plugins

**Comment by ChristopherBiscardi** [comment]
> in the upstream project

Interesting that this is a project that you don't control. (that's useful info).

---

If you don't want react-docgen's content to be processed as markdown, then the best way to do it would be to submit a PR to react-docgen to allow a config option so that the content can be labeled as `text/plain` instead of [text/markdown](https://github.com/gatsbyjs/gatsby/blob/5dc564033d367ee8516008da3e5ba69635420af4/packages/gatsby-transformer-react-docgen/src/on-node-create.js#L37). Then no markdown processing plugins will touch it.

I'm going to close this since it's not a gatsby-mdx issue, but is an issue with the react-docgen transformer's mediaType labeling.
