### ISSUE TITLE
Changing the name of an import in an MDX file doesn't refresh the scope

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#291]
From @szarouski in https://github.com/ChristopherBiscardi/gatsby-mdx/issues/284#issuecomment-464408143

My best guess is that this is either the [onCreateNode](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/0033bdfbe7c4f8b7fefbed71de4fa80f6d4678bf/packages/gatsby-mdx/gatsby/on-create-node.js#L81-L91) not writing the right files out or the [mdx-scopes loader](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/packages/gatsby-mdx/loaders/mdx-scopes.js) not depending (through webpack addDependency, etc) on the right files and thus not updating the [wrapRootElement](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/0033bdfbe7c4f8b7fefbed71de4fa80f6d4678bf/packages/gatsby-mdx/wrap-root-element.js#L6) module with the required scope, leading to the import not being defined. or a combination of these issues.

**Comment by szarouski** [comment]
I found two issues which I think have the same root:
- At first I thought that issue is with files that are not under `pages` directory. Simple test to reproduce the issue is to clone kitchen-sink example and modify `gatsby-mdx\examples\kitchen-sink\content\non-page.mdx` to import something new - you'll get a hot-reload error:
```md
import Tests from 'components/Test';

# A non-page

In not the pages directory, with nothing special about it

<Tests />
```
- In kitchen-sink I can see that hot-reloading works for items under `pages` folder. So I tried to move my content under pages folder & it didn't work. I found that it is *related* to the following rule in my gatsby-config.js:
```js
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "src",
        path: `${__dirname}/src/`
      }
    }
```
If the same rule is added to kitchen-sink example (can add it as a new rule, `posts` can remain) you'll end up with pages that look like following (I know it doesn't look good, but please bear with me):
![image](https://user-images.githubusercontent.com/911388/52926640-a0130e80-3304-11e9-9c6d-7e7a83843ae5.png)
Then if you go to /basic/ and add or modify imports - things are hot-reloading no problem. If you go to /src/basic then hot-reloading breaks. 

So it seems that only pages that have `node.internal.type === "SitePage"` work 'properly'.

**Comment by ChristopherBiscardi** [comment]
yeah, because `.mdx` (or `.js`, etc files) in `src/pages` are handled differently and go through a webpack loader instead of the import processing step. Basically, the hot-reloading issue is an issue in one code path and the `src/pages` behavior is a *different* code path which is why it works.
