### ISSUE TITLE
@mdx-js/tag dependency missing

### ISSUE THREAD

**Issue by raphadeluca** [ChristopherBiscardi/gatsby-mdx#32]
It seems we have to install @mdx-js/tag dependency  with @mdx-js/mdx.

**Comment by ChristopherBiscardi** [comment]
ah yeah, thanks for the report. We used to depend on mdx/loader which had the dependency on mdx/tag. It's now [fixed in master](https://github.com/ChristopherBiscardi/gatsby-mdx/commit/6ce478072d2a6a3c626514aac2a57c93f12328d8), but since it's only a peerDep that shouldn't block anyone from installing it manually so I'll just wait until the next release to put it out.
