### ISSUE TITLE
"Peek-Definition" and "Go to definition" in Markdown React

### ISSUE THREAD

**Issue by Ligorenko** [ChristopherBiscardi/gatsby-mdx#381]
**Is your feature request related to a problem? Please describe.**
I can't go to the definition of a component in mdx files.

**Describe the solution you'd like**
I am able to go to the definition of a component.

**Alternatives**
I configured something wrong and a friendly fellow dev helps me fix the problem.

**Additional context**
![image](https://user-images.githubusercontent.com/15678582/57038135-73129e80-6c59-11e9-96f5-bc276b82f37d.png)
![image](https://user-images.githubusercontent.com/15678582/57038305-e9af9c00-6c59-11e9-8e4d-07bc399e8998.png)

**Comment by ChristopherBiscardi** [comment]
This seems like an editor issue and not a gatsby-mdx issue. Since I don't use your editor (looks like VSCode?) I can't tell you how to fix this since I don't know what "Peek Definition" and "Go to Definition" are, nor what "Markdown React" is.

Maybe the MDX core repo would know, but I don't think the code for any of what you're talking about lives there, so maybe open up an issue on whoever implements the code for the functions you're talking about
