### ISSUE TITLE
Using the same name for importing different files in different pages results in overwriting

### ISSUE THREAD

**Issue by tareefdev** [ChristopherBiscardi/gatsby-mdx#388]
**Describe the bug**
Using the same name to import different MDX files inside different pages results in overwriting.

**To Reproduce**
- Clone [the repo](https://github.com/tareefdev/mdx-starter), install node packages and develop it.
- Open those two pages:
http://localhost:8000/en-generated-url/
http://localhost:8000/ar-generated-url/
- The first page has `import About from './about.mdx';` and the second one `import About from './about_ar.mdx';`, although both URLs will show just one page (about_ar.mdx) due to using the same component name.

**Expected behavior**
Every page should show the imported file within it.

**Additional context**
I'm not sure if this a bug or expected behavior. If it's so, how I could manage which names I used before to not re-use them again.

**Comment by ChristopherBiscardi** [comment]
This is because of the way scope gets included in the final site. Conceptually it's as if there is a single object with all of the imports across all of the MDX files `Object.assign`ed into a single object. It's expected behavior, but not ideal. We talked a bit last week about potential future improvements that would let us dynamically load components per-generated-page but that won't happen for awhile.

In this case for the short-term I'd import as `About` and `AboutAR` since they're different components.

**Comment by tareefdev** [comment]
Ok, thanks for helping.
