### ISSUE TITLE
style omited in production env when reload page

### ISSUE THREAD

**Issue by meritozh** [ChristopherBiscardi/gatsby-mdx#394]
**Describe the bug**

I use `MDXProvider` to override default components to achieve code highlight. Everything is ok in development env, but in production env, if I reload current page, style injectted by `wrapRootElement` omitted.

**To Reproduce**
[demo](https://github.com/meritozh/gatsby-mdx-minimal-repro)

1. clone this demo repo
2. yarn install
3. npx gatsby build
4. npx gatsby serve
5. open `http://localhost:9000`, jump to **page-3**, code highlight works well.
6. reload page, highlight lost.

**Screenshots**

![Screen Shot 2019-05-28 at 4 06 17 PM](https://user-images.githubusercontent.com/7543300/58461658-bed63c00-8162-11e9-95de-b47a0bc4b345.png)

### reload:

![Screen Shot 2019-05-28 at 4 06 26 PM](https://user-images.githubusercontent.com/7543300/58461646-bc73e200-8162-11e9-9751-d896c45549b1.png)

**Comment by meritozh** [comment]
I'm not sure it is caused by `gatsby-plugin-mdx` (1.0), need test

**Comment by ChristopherBiscardi** [comment]
Because the `wrapRootElement` isn't used in `gatsby-ssr`, the styles are not included until the gatsby-browser processing runs. Add the `wrapRootElement` that you use in `gatsby-browser` to `gatsby-ssr` as well.

let me know if this doesn't fix your issue :)

**Comment by meritozh** [comment]
@ChristopherBiscardi Yes, it works now, but I'm confused.

See the second snapshot, the code is highlighted.

https://github.com/meritozh/gatsby-mdx-minimal-repro/blob/dd93b785ff16b9e6227c29a51c8cf07a2bbdcee1/src/wrap-root-element.js#L7-L14

Only the background color omitted, because it omit the class name `language-c` if I reload _page 3_:

![image](https://user-images.githubusercontent.com/7543300/58605042-1ee6f280-82c9-11e9-8053-e0ba8cd9cac9.png)

https://github.com/meritozh/gatsby-mdx-minimal-repro/blob/dd93b785ff16b9e6227c29a51c8cf07a2bbdcee1/src/style/prism-react-dark.scss#L46-L49

**It doesn't omit the class name `token` `keyword` which produced by `prism-react-renderer`**.

But If I first route to _homepage_, then jump to _page 3_, everything is ok:

![image](https://user-images.githubusercontent.com/7543300/58605113-52298180-82c9-11e9-8c49-7c8fc5b5a5e0.png)

Why the output is not consistent?

**Comment by ChristopherBiscardi** [comment]
The output is not consistent in that repo because the `gatsby-ssr` and `gatsby-browser` include different `MDXProvider` components (`ssr` has none, `browser` has the `Code`), which means the prism-react-renderer component is only being applied by `gatsby-browser`. The HTML generated by `gatsby build` is generated with `gatsby-ssr`, resulting in the original set of HTML. The "second rendering" is done at runtime via with the additional code components however, there's a difference between the first runtime render and the runtime render when switching pages. The first runtime render (when refreshing page-3) causes a rehydration of React on top of the original HTML. The second runtime render (when switching pages) is generating brand new DOM without the underlying HTML.

So while I haven't investigated this in depth in this case, my best guess as to why there's a difference is that the rehydration render when combined with the original "faulty" HTML causes React to short-circuit some of it's reconciliation when compared to the "raw" render, which renders completely from scratch. It's like having some stale state around.
