### ISSUE TITLE
update npm for gatsby-plugin-mdx to show up the deprecation notice

### ISSUE THREAD

**Issue by muescha** [ChristopherBiscardi/gatsby-mdx#398]
**Describe the bug**

the npm readme for the gatsby-plugin-mdx is not up to date

**To Reproduce**
- i am at the gatsbyjs site
- i search for mdx
- i see this plugin description https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/?=mdx
- i see an old readme
- i open the github repo https://github.com/ChristopherBiscardi/gatsby-plugin-mdx and see an deprecation notice 

**Expected behavior**
- i see a deprecation notice on the gatsbyjs plugin page
https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/
- i see a deprecation notice on the npm plugin page 
https://www.npmjs.com/package/gatsby-plugin-mdx

**Screenshots**
n/a

**Additional context**
n/a

**Comment by ChristopherBiscardi** [comment]
gatsby-plugin-mdx became the 1.0 of gatsby-mdx. We haven't announced it yet and expect that everyone will be using gatsby-mdx until we announce it because gatsby-plugin-mdx only ever got a low number of downloads. Since it is deployed, you can use gatsby-plugin-mdx 1.0+ instead of gatsby-mdx if you so wish before we announce it. That is why it is not deprecated. The old repo is however, which is why there's a deprecation notice there.
