### ISSUE TITLE
defaultLayouts and wrappers

### ISSUE THREAD

**Issue by ChristopherBiscardi** [ChristopherBiscardi/gatsby-mdx#50]
[mdx-deck](https://github.com/jxnblk/mdx-deck) uses the default export (read: default layout) as a container for each individual slide.

- [ ] create a new pre-mdx-deck loader
- [ ] pull default export logic out of mdx-loader into a util. Use that logic in pre-mdx-loader as well
- [ ] introduce the concept of a wrapper? may not need this and will leave it for a second PR.

# Layouts and Wrappers

Layouts are an MDX concept. They are correlate directly to the default export of an mdx file. In regular mdx files, this means they end up wrapping the entire page. In mdx-deck files, they wrap each individual slide. Which raises the question: Do we need a wrapper that is page level? Is something like having a presentation couched in the navigation, etc of a website useful? I'd think so.

**Comment by ChristopherBiscardi** [comment]
As indicated in https://github.com/ChristopherBiscardi/gatsby-mdx/issues/47#issuecomment-410962298, It's useful to have wrappers to abstract things like page queries across a set of blog posts, for example.

So the main use case for wrappers is

- write a pageQuery once and re-use it across a set of .mdx files. 

While mdx hoists non-react statics, I don't think gatsby would find a graphql query on a react component (meaning that you couldn't define a graphql pageQuery on a layout and have it hoisted into the mdx component, then found by gatsby).

**Comment by geddski** [comment]
it's also especially useful that pageQueries can use frontmatter values as part of the query params.

**Comment by avigoldman** [comment]
It sounds like we are talking about using wrappers for 2 separate things:
1. Wrapping entire MDX slide decks – not the individual pages
1. Wrapping pages similarly to how the `component` is used when creating pages with the remark transformer – the `component` has a single GraphQL query that can be dynamic.

Regarding number two, I think that we should revisit #13. Instead of duplicating the way that Gatsby handles dynamic queries and templates, we can enable people to follow the same pattern that they follow with the `html` field from the remark transformer. 

If we follow the patterns used in [@mdx/realtime](https://github.com/mdx-js/mdx/blob/master/packages/runtime/src/index.js), we should be able to implement this. We could do the [MDX and ES5 transform](https://github.com/mdx-js/mdx/blob/master/packages/runtime/src/index.js#L20) in the GraphQL step, and wrap the transpiled code inside the [`new Function`](https://github.com/mdx-js/mdx/blob/master/packages/runtime/src/index.js#L24) in the `importMDX` helper. 

Also completely possible I've misunderstood what we are talking about here 😅

**Comment by ChristopherBiscardi** [comment]
yeah, I may implement the runtime stuff tomorrow [on stream](https://twitter.com/chrisbiscardi/status/1026988776164192256). Think it'd be a cool topic and it would definitely be an interesting development.

we'll see how it turns out. Will post here afterward.

**Comment by ChristopherBiscardi** [comment]
The ability to use mdx content in the same manner as html content from the remark transformer exists now. That should be used in the meantime while we consider what "Wrappers vs Layouts" should look like. I think wrappers will still be required for filesystem local requires (since mdx files can be used directly as the component in a createPage call and this seems to be simpler for people to understand for now) to reach parity with the graphql approach.

**Comment by loremipson** [comment]
> The ability to use mdx content in the same manner as html content from the remark transformer exists now. 

Is this documented anywhere yet? Having some troubles with this at the moment.

**Comment by ChristopherBiscardi** [comment]
@loremipson not documented unfortunately (need to do that tomorrow) but it is how we do all of the example projects and our docs site, so you can check out the graphql query and `componentWithMDXScope` function in the [docs](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/examples/docs/gatsby-node.js#L37) code, and also the [`MDXRenderer` usage](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/16632a07174fc5972eecc68b9ebc6e32bc4160c5/examples/docs/src/docs-layout.js#L48) in the page component. You'll also need to source the mdx files with the [filesystem source](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/16632a07174fc5972eecc68b9ebc6e32bc4160c5/examples/docs/gatsby-config.js#L13-L17) in gatsby-config.

I'm happy to help you through it if you want to file a separate issue.

**Comment by johno** [comment]
Going to close this since mdx-deck is no longer supported for the time being and pageQueries can be shared via a template and [programmatic page creation](https://gatsby-mdx.netlify.com/guides/programmatically-creating-pages.
