### ISSUE TITLE
Export default in code block breaks layout

### ISSUE THREAD

**Issue by jeroenransijn** [ChristopherBiscardi/gatsby-mdx#75]
When I use a code block and in that code block write `export default` things start to break.

![image](https://user-images.githubusercontent.com/564463/44505092-58ad0d80-a654-11e8-9f24-fee35138cc67.png)

Before | After
---|---
![image](https://user-images.githubusercontent.com/564463/44505158-9d38a900-a654-11e8-850d-84b8245df803.png) |  ![image](https://user-images.githubusercontent.com/564463/44505140-88f4ac00-a654-11e8-87d3-3c682f096ce9.png)

**Comment by ChristopherBiscardi** [comment]
This is due to the way we detect [default exports right now](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/5426765be4f4e5fa7aa2769144a06f789e7c1f4b/packages/gatsby-mdx/mdx-loader.js#L8). We should improve this check to be AST based so it skips code blocks, paragraphs, etc and just looks into the JSX blocks.

**Comment by ChristopherBiscardi** [comment]
@jeroenransijn This fix is published in 0.0.14. Let me know if you're still running into issues :)
