### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ManuelHaag** [ChristopherBiscardi/gatsby-mdx#77]
**Describe the bug**

The layout example from the readme does not work.

````
 ERROR  Failed to compile with 1 errors                                                                                                                                                                  11:02:42
This dependency was not found:

* C:pathtoprojectgatsby-mdx-testsrccomponentsdefault-layout.jsx in ./src/posts/test.mdx

To install it, you can run: npm install --save C:pathtoprojectgatsby-mdx-testsrccomponentsdefault-layout.jsx
× ｢wdm｣:
ERROR in ./src/posts/test.mdx
Module not found: Error: Can't resolve 'C:pathtoprojectgatsby-mdx-testsrccomponentsdefault-layout.jsx' in 'C:\path\to\project\gatsby-mdx-test\src\posts'
 @ ./src/posts/test.mdx 12:0-90 20:12-25
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false C://path//to//project//gatsby-mdx-test//.cache//app
i ｢wdm｣: Failed to compile.
````

**To Reproduce**
1. `gatsby new gatsby-mdx-test https://github.com/kripod/gatsby-starter-modern` (e.g. inside `C:\path\to\project\`)
2. `yarn add gatsby-mdx @mdx-js/mdx @mdx-js/tag gatsby-source-filesystem`
3. `gatsby-config.js`

````js
module.exports = {
  siteMetadata: {
    title: 'Gatsby Modern Starter',
    language: 'en',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-styled-components',

    {
      resolve: `gatsby-mdx`,
      options: {
        defaultLayouts: {
          posts: require.resolve('./src/components/posts-layout.jsx'),
          default: require.resolve('./src/components/default-layout.jsx'),
        },
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `posts`,
        path: `${__dirname}/src/posts/`,
      },
    },
  ],
};
````

4. `gatsby-node.js`

````js
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;
  return new Promise((resolve, reject) => {
    resolve(
      graphql(
        `
          {
            allMdx {
              edges {
                node {
                  fileAbsolutePath
                  fileNode {
                    name
                  }
                }
              }
            }
          }
        `,
      ).then(result => {
        if (result.errors) {
          console.log(result.errors);
          reject(result.errors);
        }

        // Create blog posts pages.
        result.data.allMdx.edges.forEach(({ node }) => {
          createPage({
            path: `/non-page/${node.fileNode.name}`,
            component: node.fileAbsolutePath, // blogPost,
            context: { absPath: node.fileAbsolutePath },
          });
        });
      }),
    );
  });
};
````

5.  `src/posts/test.mdx`

````md
# My first MDX Page

some awesome content
````

6. `src/components/default-layout.jsx` and `src/components/posts-layout.jsx`

````jsx
import React from 'react';

export default ({ children }) => (
  <div>
    <h1>My Layout</h1>
    <div>{children}</div>
  </div>
);
````

**Expected behavior**
The `posts-layout.jsx` should be loaded, as the `sourceInstanceName` for `src/posts` is `posts`. Instead, the `default-layout.jsx` is loaded, which then can't resolve. Multiple things going wrong here.

**Additional context**
- `Windows 10`
- `node v10.1.0`
- `yarn 1.7.0`
- `gatsby-cli 1.1.58`

**Comment by ChristopherBiscardi** [comment]
Hey @ManuelHaag, thanks for filing an issue. Unfortunately I don't own a windows computer so don't really know what could be going wrong here.

The path `C:pathtoprojectgatsby-mdx-testsrccomponentsdefault-layout.jsx` definitely looks weird. Is that verbatim output from the console or was anything replaced?

It looks like the mdx default export *is* being sucessfully replaced but the path that imports the layout is wonky. Can you run develop with `DEBUG=gatsby-mdx*` [as shown here](https://github.com/visionmedia/debug#windows-command-prompt-notes), which [should trigger this debug output](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/9d794741b61ea1d65229f2967e9a6e8c0479bafd/packages/gatsby-mdx/mdx-loader.js#L103) and will show you the absolute path of the required export.

You can also try to use `path.resolve` instead of `require.resolve` for the layouts. I'm not sure if there's behavioral differences for require between *nix and windows systems.
